LTE_BASE = 0xB000

LOG_LTE_MAC_DL_TRANSPORT_BLOCK = 0x063
LOG_LTE_MAC_UL_TRANSPORT_BLOCK = 0x064
LOG_LTE_ML1_SERVING_CELL_MEAS_AND_EVAL = 0x17F
LOG_LTE_ML1_NEIGHBOR_MEASUREMENTS = 0x180
LOG_LTE_ML1_MAC_RAR_MSG1_REPORT = 0x167
LOG_LTE_ML1_MAC_RAR_MSG2_REPORT = 0x168
LOG_LTE_ML1_MAC_UE_IDENTIFICATION_MESSAGE_MSG3_REPORT = 0x169
LOG_LTE_ML1_MAC_CONTENTION_RESOLUTION_MESSAGE_MSG4_REPORT = 0x16A
LOG_LTE_ML1_CONNECTED_MODE_INTRA_FREQ_MEAS = 0x179
LOG_LTE_ML1_NEIGHBOR_CELL_MEAS_REQ_RESPONSE = 0x192
LOG_LTE_ML1_SERVING_CELL_MEAS_RESPONSE = 0x193
LOG_LTE_ML1_SEARCH_REQ_RESPONSE = 0x194
LOG_LTE_ML1_CONNECTED_MODE_NEIGHBOR_MEAS_REQ_RESPONSE = 0x195
LOG_LTE_ML1_SERVING_CELL_INFO = 0x197
LOG_LTE_PHY_PDSCH_DEMAPPER_CONFIG = 0x126
LOG_LTE_PHY_PDCCH_DECODING_RESULT = 0x130
LOG_LTE_PHY_PDCCH_DECODING_RESULT2 = 0x132
LOG_LTE_PHY_PUSCH_TX_REPORT = 0x139
LOG_LTE_PHY_PUCCH_TX_REPORT = 0x13C
LOG_LTE_PHY_PUSCH_CSF_REPORT = 0x140
LOG_LTE_PHY_PDSCH_STAT_INDICATION = 0x144
LOG_LTE_PHY_PDCCH_PHICH_INDICATION = 0x16B
LOG_LTE_PHY_GM_TX_REPORT = 0x16D
LOG_LTE_PHY_PDSCH_STAT_INDICATION2 = 0x173
LOG_LTE_PHY_PUSCH_STAT_INDICATION = 0x174
LOG_LTE_PHY_PUCCH_CSF_REPORT = 0x175
LOG_LTE_PHY_CQI_REPORT = 0x176
LOG_LTE_PHY_RI_REPORT = 0x177
LOG_LTE_PHY_PMI_REPORT = 0x178
LOG_LTE_RRC_OTA_MESSAGE = 0x0C0
LOG_LTE_RRC_MIB_MESSAGE = 0x0C1
LOG_LTE_RRC_SERVING_CELL_INFO = 0x0C2
LOG_LTE_RRC_SUPPORTED_CA_COMBOS = 0x0CD

LOG_5GNR_NAS_5GMM_STATE = 0x80C
LOG_5GNR_RRC_OTA_MESSAGE = 0x821
LOG_5GNR_RRC_MIB_INFO = 0x822
LOG_5GNR_RRC_SERVING_CELL_INFO = 0x823
LOG_5GNR_RRC_CONFIGURATION_INFO = 0x825
LOG_5GNR_RRC_SUPPORTED_CA_COMBOS = 0x826
LOG_5GNR_MAC_RACH_ATTEMPT = 0x88A
LOG_5GNR_ML1_MEAS_DATABASE_UPDATE = 0x97F

NAMES = {
    LTE_BASE + LOG_LTE_MAC_DL_TRANSPORT_BLOCK: "lte_mac_dl_transport_block",
    LTE_BASE + LOG_LTE_MAC_UL_TRANSPORT_BLOCK: "lte_mac_ul_transport_block",
    LTE_BASE + LOG_LTE_ML1_MAC_RAR_MSG1_REPORT: "lte_ml1_mac_rar_msg1_report",
    LTE_BASE + LOG_LTE_ML1_MAC_RAR_MSG2_REPORT: "lte_ml1_mac_rar_msg2_report",
    LTE_BASE + LOG_LTE_ML1_MAC_UE_IDENTIFICATION_MESSAGE_MSG3_REPORT: "lte_ml1_mac_msg3_report",
    LTE_BASE + LOG_LTE_ML1_MAC_CONTENTION_RESOLUTION_MESSAGE_MSG4_REPORT: "lte_ml1_mac_msg4_report",
    LTE_BASE + LOG_LTE_ML1_CONNECTED_MODE_INTRA_FREQ_MEAS: "lte_ml1_connected_intra_freq_meas",
    LTE_BASE + LOG_LTE_ML1_SERVING_CELL_MEAS_AND_EVAL: "lte_ml1_serving_cell_meas",
    LTE_BASE + LOG_LTE_ML1_NEIGHBOR_MEASUREMENTS: "lte_ml1_neighbor_measurements",
    LTE_BASE + LOG_LTE_ML1_NEIGHBOR_CELL_MEAS_REQ_RESPONSE: "lte_ml1_neighbor_cell_meas_req_response",
    LTE_BASE + LOG_LTE_ML1_SERVING_CELL_MEAS_RESPONSE: "lte_ml1_serving_cell_meas_response",
    LTE_BASE + LOG_LTE_ML1_SEARCH_REQ_RESPONSE: "lte_ml1_search_req_response",
    LTE_BASE + LOG_LTE_ML1_CONNECTED_MODE_NEIGHBOR_MEAS_REQ_RESPONSE: "lte_ml1_connected_neighbor_meas_req_response",
    LTE_BASE + LOG_LTE_ML1_SERVING_CELL_INFO: "lte_ml1_serving_cell_info",
    LTE_BASE + LOG_LTE_PHY_PDSCH_DEMAPPER_CONFIG: "lte_phy_pdsch_demapper_config_candidate",
    LTE_BASE + LOG_LTE_PHY_PDCCH_DECODING_RESULT: "lte_phy_pdcch_decoding_result_candidate",
    LTE_BASE + LOG_LTE_PHY_PDCCH_DECODING_RESULT2: "lte_phy_pdcch_decoding_result2_candidate",
    LTE_BASE + LOG_LTE_PHY_PUSCH_TX_REPORT: "lte_phy_pusch_tx_report_candidate",
    LTE_BASE + LOG_LTE_PHY_PUCCH_TX_REPORT: "lte_phy_pucch_tx_report_candidate",
    LTE_BASE + LOG_LTE_PHY_PUSCH_CSF_REPORT: "lte_phy_pusch_csf_report_candidate",
    LTE_BASE + LOG_LTE_PHY_PDSCH_STAT_INDICATION: "lte_phy_pdsch_stat_indication_candidate",
    LTE_BASE + LOG_LTE_PHY_PDCCH_PHICH_INDICATION: "lte_phy_pdcch_phich_indication_candidate",
    LTE_BASE + LOG_LTE_PHY_GM_TX_REPORT: "lte_phy_gm_tx_report_candidate",
    LTE_BASE + LOG_LTE_PHY_PDSCH_STAT_INDICATION2: "lte_phy_pdsch_stat_indication2_candidate",
    LTE_BASE + LOG_LTE_PHY_PUSCH_STAT_INDICATION: "lte_phy_pusch_stat_indication_candidate",
    LTE_BASE + LOG_LTE_PHY_PUCCH_CSF_REPORT: "lte_phy_pucch_csf_report_candidate",
    LTE_BASE + LOG_LTE_PHY_CQI_REPORT: "lte_phy_cqi_report_candidate",
    LTE_BASE + LOG_LTE_PHY_RI_REPORT: "lte_phy_ri_report_candidate",
    LTE_BASE + LOG_LTE_PHY_PMI_REPORT: "lte_phy_pmi_report_candidate",
    LTE_BASE + LOG_LTE_RRC_OTA_MESSAGE: "lte_rrc_ota_message",
    LTE_BASE + LOG_LTE_RRC_MIB_MESSAGE: "lte_rrc_mib",
    LTE_BASE + LOG_LTE_RRC_SERVING_CELL_INFO: "lte_rrc_serving_cell_info",
    LTE_BASE + LOG_LTE_RRC_SUPPORTED_CA_COMBOS: "lte_rrc_supported_ca_combos",
    LTE_BASE + LOG_5GNR_NAS_5GMM_STATE: "nr_nas_5gmm_state",
    LTE_BASE + LOG_5GNR_RRC_OTA_MESSAGE: "nr_rrc_ota_message",
    LTE_BASE + LOG_5GNR_RRC_MIB_INFO: "nr_rrc_mib_info",
    LTE_BASE + LOG_5GNR_RRC_SERVING_CELL_INFO: "nr_rrc_serving_cell_info",
    LTE_BASE + LOG_5GNR_RRC_CONFIGURATION_INFO: "nr_rrc_configuration_info",
    LTE_BASE + LOG_5GNR_RRC_SUPPORTED_CA_COMBOS: "nr_rrc_supported_ca_combos",
    LTE_BASE + LOG_5GNR_MAC_RACH_ATTEMPT: "nr_mac_rach_attempt",
    LTE_BASE + LOG_5GNR_ML1_MEAS_DATABASE_UPDATE: "nr_ml1_meas_database_update",
}


PROBE_SCHEDULING_ITEMS = [
    LOG_LTE_ML1_MAC_RAR_MSG1_REPORT,
    LOG_LTE_ML1_MAC_RAR_MSG2_REPORT,
    LOG_LTE_ML1_MAC_UE_IDENTIFICATION_MESSAGE_MSG3_REPORT,
    LOG_LTE_ML1_MAC_CONTENTION_RESOLUTION_MESSAGE_MSG4_REPORT,
    LOG_LTE_ML1_CONNECTED_MODE_INTRA_FREQ_MEAS,
    LOG_LTE_ML1_NEIGHBOR_CELL_MEAS_REQ_RESPONSE,
    LOG_LTE_ML1_SEARCH_REQ_RESPONSE,
    LOG_LTE_ML1_CONNECTED_MODE_NEIGHBOR_MEAS_REQ_RESPONSE,
    LOG_5GNR_MAC_RACH_ATTEMPT,
]

PROBE_SCHEDULING_LOG_IDS = {LTE_BASE + item for item in PROBE_SCHEDULING_ITEMS}


PROBE_PHY_ITEMS = [
    LOG_LTE_PHY_PDSCH_DEMAPPER_CONFIG,
    LOG_LTE_PHY_PDCCH_DECODING_RESULT,
    LOG_LTE_PHY_PDCCH_DECODING_RESULT2,
    LOG_LTE_PHY_PUSCH_TX_REPORT,
    LOG_LTE_PHY_PUCCH_TX_REPORT,
    LOG_LTE_PHY_PUSCH_CSF_REPORT,
    LOG_LTE_PHY_PDSCH_STAT_INDICATION,
    LOG_LTE_PHY_PDCCH_PHICH_INDICATION,
    LOG_LTE_PHY_GM_TX_REPORT,
    LOG_LTE_PHY_PDSCH_STAT_INDICATION2,
    LOG_LTE_PHY_PUSCH_STAT_INDICATION,
    LOG_LTE_PHY_PUCCH_CSF_REPORT,
    LOG_LTE_PHY_CQI_REPORT,
    LOG_LTE_PHY_RI_REPORT,
    LOG_LTE_PHY_PMI_REPORT,
]

PROBE_PHY_LOG_IDS = {LTE_BASE + item for item in PROBE_PHY_ITEMS}


def metric_log_items(enable_mac: bool = False, probe_scheduling: bool = False, probe_phy: bool = False) -> list[int]:
    items = [
        LOG_LTE_ML1_SERVING_CELL_MEAS_AND_EVAL,
        LOG_LTE_ML1_NEIGHBOR_MEASUREMENTS,
        LOG_LTE_ML1_SERVING_CELL_MEAS_RESPONSE,
        LOG_LTE_ML1_SERVING_CELL_INFO,
        LOG_LTE_RRC_OTA_MESSAGE,
        LOG_LTE_RRC_MIB_MESSAGE,
        LOG_LTE_RRC_SERVING_CELL_INFO,
        LOG_LTE_RRC_SUPPORTED_CA_COMBOS,
        LOG_5GNR_NAS_5GMM_STATE,
        LOG_5GNR_RRC_OTA_MESSAGE,
        LOG_5GNR_RRC_MIB_INFO,
        LOG_5GNR_RRC_SERVING_CELL_INFO,
        LOG_5GNR_RRC_CONFIGURATION_INFO,
        LOG_5GNR_RRC_SUPPORTED_CA_COMBOS,
        LOG_5GNR_ML1_MEAS_DATABASE_UPDATE,
    ]
    if enable_mac:
        items += [LOG_LTE_MAC_DL_TRANSPORT_BLOCK, LOG_LTE_MAC_UL_TRANSPORT_BLOCK]
    if probe_scheduling:
        items += PROBE_SCHEDULING_ITEMS
    if probe_phy:
        items += PROBE_PHY_ITEMS
    return items
